### ISSUE TITLE
applying weights to survey data

### ISSUE THREAD

**Issue by ernestguevarra** [nutriverse/ipctools#38]
@tomaszaba I noticed that the way IPC calculates prevalence based on what you have been showing in your approach is that no survey weights are being applied to account for the cluster design of the survey/s that produced the data. For example, in your South Sudan example, you basically just calculate prevalence by doing a simple number of SAM divided by total number of kids in sample.

Does IPC just automatically assume that the PPS done at the start was followed strictly as per design? From my experience, very rarely do survey data come up as designed and samples per cluster is never always what is expected. For S3M and RAM type surveys that Mark and I have developed, this doesn't matter too much as we always do weighting posteriorly (we don't do PPS). But, for a PPS design in which the weights are applied right from the sampling itself, having a sample that is different from your intended design has implications in the balance of your dataset such that a simple number of SAM cases divided by all 6-59 in sample will give biased results.

Do you guys don't do any weighting at all on the data to calculate prevalence?

**Comment by ernestguevarra** [comment]
from  my understanding, the way IPC is calculating prevalence on PPS datasets is what is recommended by SMART as well? and this is the approach that is implemented by the SMART ENA tool?

**Comment by tomaszaba** [comment]
Hi @ernestguevarra , 

The analysis approach employed in IPC is very much the same of that applied/recommended in SMART. They call it self-weighted. and yes, they assume that the design was executed precisely. In SMART survey, weights are only considered to be  applied when survey data is to be re-analyzed at higher admin level. For instance, four surveys where done at district level of a province and there is a need to report on a provincial level prevalence estimate. Here is when they consider applying weights in the merged dataset. 

So the IPC follows very much that same approach, but rarely we require merging survey data, but when we do, we apply weights. 

In that example data from South Sudan, that was not a survey per se (with all those details, etc) - it was just a muac "screening" they had incorporated in a food security assessment, where this latter, had a very small sample size of 6 clusters * 14 households per cluster. That is why the number of children 6-59 months was too small.

**Comment by ernestguevarra** [comment]
> Hi @ernestguevarra ,
> 
> The analysis approach employed in IPC is very much the same of that applied/recommended in SMART. They call it self-weighted. and yes, they assume that the design was executed precisely. In SMART survey, weights are only considered to be applied when survey data is to be re-analyzed at higher admin level. For instance, four surveys where done at district level of a province and there is a need to report on a provincial level prevalence estimate. Here is when they consider applying weights in the merged dataset.
> 
> So the IPC follows very much that same approach, but rarely we require merging survey data, but when we do, we apply weights.
> 
> In that example data from South Sudan, that was not a survey per se (with all those details, etc) - it was just a muac "screening" they had incorporated in a food security assessment, where this latter, had a very small sample size of 6 clusters * 14 households per cluster. That is why the number of children 6-59 months was too small.

OK. The combining of results from smaller surveys is technically not weighting but a stratified analysis.

Anyway, that confirms my suspicion. Thanks.
